[alias]
xtask = "run --package xtask --"

[target.riscv32i-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "force-unwind-tables",
  "-C", "link-arg=-Teh_frame.ld"
]

[target.riscv32im-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "force-unwind-tables",
  "-C", "link-arg=-Teh_frame.ld"
]

[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "force-unwind-tables",
  "-C", "link-arg=-Teh_frame.ld"
]