use crate::teletext::TeletextChar;

/// Enum of all possible language specific teletext character-sets
#[allow(dead_code)]
#[derive(Debug, Default, Copy, Clone)]
pub enum NationalOptionCharacterSubset {
    #[default]
    English,
    German,
    Swedish,
    Finnish,
    Hungarian,
    Italian,
    French,
    Portuguese,
    Spanish,
    Czech,
    Slovak,
}

/// Enum of all possible diacriticals
#[derive(Debug, Default, Copy, Clone)]
pub enum Diacritical {
    #[default]
    /// Character has no diacritical
    None,
    /// Diacritical: `
    Grave,
    /// Diacritical: ´
    Acute,
    /// Diacritical: ˆ
    Circumflex,
    /// Diacritical: ˜
    Tilde,
    /// Diacritical: ¯
    Macron,
    /// Diacritical: ˘
    Breve,
    /// Diacritical: ˙
    Dot,
    /// Diacritical:  ̈
    Umlaut,
    /// Diacritical:  ̣
    DotBelow,
    /// Diacritical:  ̊
    Ring,
    /// Diacritical:  ̧
    Cedilla,
    /// Diacritical: ̱
    #[allow(dead_code)]
    LowLine,
    /// Diacritical: ˝
    DoubleAcute,
    /// Diacritical: ˛
    Ogonek,
    /// Diacritical:  ̌
    Caron,
}

/// Marks in which type of character-set a character can be found
#[derive(Debug, Clone, Copy)]
pub enum CharacterSet {
    G0,
    G0WithDiacritical(Diacritical),
    G2,
    G3,
}

impl NationalOptionCharacterSubset {
    /// Checks if a [NationalOptionCharacterSubset] includes a specific character and if it includes it, the teletext encoding of that character is returned
    ///
    /// # Arguments
    /// * `ch` - Character that is checked
    fn has_char(&self, ch: char) -> Option<u8> {
        use NationalOptionCharacterSubset::*;

        match self {
            English => ENGLISH_TELETEXT_CHARS(ch),
            German => GERMAN_TELETEXT_CHARS(ch),
            _ => todo!("National character subset not implemented!"),
        }
    }
}

impl Diacritical {
    /// Encodes a diacritical into its teletext encoding
    pub fn code(&self) -> u8 {
        match self {
            Diacritical::None => 0x0,
            Diacritical::Grave => 0x1,
            Diacritical::Acute => 0x2,
            Diacritical::Circumflex => 0x3,
            Diacritical::Tilde => 0x4,
            Diacritical::Macron => 0x5,
            Diacritical::Breve => 0x6,
            Diacritical::Dot => 0x7,
            Diacritical::Umlaut => 0x8,
            Diacritical::DotBelow => 0x9,
            Diacritical::Ring => 0xA,
            Diacritical::Cedilla => 0xB,
            Diacritical::LowLine => 0xC,
            Diacritical::DoubleAcute => 0xD,
            Diacritical::Ogonek => 0xE,
            Diacritical::Caron => 0xF,
        }
    }
}

/// Returns the teletext encoding of a character if the english character-set contains it
static ENGLISH_TELETEXT_CHARS: fn(char) -> Option<u8> = |input_char| {
    Some(match input_char {
        '£' => 0x23,
        '$' => 0x24,
        '@' => 0x40,
        '←' => 0x5B,
        '½' => 0x5C,
        '→' => 0x5D,
        '↑' => 0x5E,
        '#' => 0x5F,
        '—' => 0x60,
        '¼' => 0x7B,
        '‖' => 0x7C,
        '¾' => 0x7D,
        '÷' => 0x7E,
        _ => return None,
    })
};

/// Returns the teletext encoding of a character if the german character-set contains it
static GERMAN_TELETEXT_CHARS: fn(char) -> Option<u8> = |input_char| {
    Some(match input_char {
        '#' => 0x23,
        '$' => 0x24,
        '§' => 0x40,
        'Ä' => 0x5B,
        'Ö' => 0x5C,
        'Ü' => 0x5D,
        '^' => 0x5E,
        '_' => 0x5F,
        '°' => 0x60,
        'ä' => 0x7B,
        'ö' => 0x7C,
        'ü' => 0x7D,
        'ß' => 0x7E,
        _ => return None,
    })
};

/// Returns a tuple of the teletext encoding, on which [CharacterSet] the character is found and if the character needs a diacritical
static LATIN_TELETEXT_CHARS: fn(char) -> Option<(u8, CharacterSet)> = |input_char| {
    Some(match input_char {
        ' ' => (0x20, CharacterSet::G0),
        '!' => (0x21, CharacterSet::G0),
        '"' => (0x22, CharacterSet::G0),
        '#' => (0x23, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '¤' => (0x24, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '%' => (0x25, CharacterSet::G0),
        '&' => (0x26, CharacterSet::G0),
        '\'' => (0x27, CharacterSet::G0),
        '(' => (0x28, CharacterSet::G0),
        ')' => (0x29, CharacterSet::G0),
        '*' => (0x2A, CharacterSet::G0),
        '+' => (0x2B, CharacterSet::G0),
        ',' => (0x2C, CharacterSet::G0),
        '-' => (0x2D, CharacterSet::G0),
        '.' => (0x2E, CharacterSet::G0),
        '/' => (0x2F, CharacterSet::G0),

        '0' => (0x30, CharacterSet::G0),
        '1' => (0x31, CharacterSet::G0),
        '2' => (0x32, CharacterSet::G0),
        '3' => (0x33, CharacterSet::G0),
        '4' => (0x34, CharacterSet::G0),
        '5' => (0x35, CharacterSet::G0),
        '6' => (0x36, CharacterSet::G0),
        '7' => (0x37, CharacterSet::G0),
        '8' => (0x38, CharacterSet::G0),
        '9' => (0x39, CharacterSet::G0),
        ':' => (0x3A, CharacterSet::G0),
        ';' => (0x3B, CharacterSet::G0),
        '<' => (0x3C, CharacterSet::G0),
        '=' => (0x3D, CharacterSet::G0),
        '>' => (0x3E, CharacterSet::G0),
        '?' => (0x3F, CharacterSet::G0),

        '@' => (0x40, CharacterSet::G0WithDiacritical(Diacritical::None)),
        'A' => (0x41, CharacterSet::G0),
        'B' => (0x42, CharacterSet::G0),
        'C' => (0x43, CharacterSet::G0),
        'D' => (0x44, CharacterSet::G0),
        'E' => (0x45, CharacterSet::G0),
        'F' => (0x46, CharacterSet::G0),
        'G' => (0x47, CharacterSet::G0),
        'H' => (0x48, CharacterSet::G0),
        'I' => (0x49, CharacterSet::G0),
        'J' => (0x4A, CharacterSet::G0),
        'K' => (0x4B, CharacterSet::G0),
        'L' => (0x4C, CharacterSet::G0),
        'M' => (0x4D, CharacterSet::G0),
        'N' => (0x4E, CharacterSet::G0),
        'O' => (0x4F, CharacterSet::G0),
        'P' => (0x50, CharacterSet::G0),
        'Q' => (0x51, CharacterSet::G0),
        'R' => (0x52, CharacterSet::G0),
        'S' => (0x53, CharacterSet::G0),
        'T' => (0x54, CharacterSet::G0),
        'U' => (0x55, CharacterSet::G0),
        'V' => (0x56, CharacterSet::G0),
        'W' => (0x57, CharacterSet::G0),
        'X' => (0x58, CharacterSet::G0),
        'Y' => (0x59, CharacterSet::G0),
        'Z' => (0x5A, CharacterSet::G0),
        '[' => (0x5B, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '\\' => (0x5C, CharacterSet::G0WithDiacritical(Diacritical::None)),
        ']' => (0x5D, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '^' => (0x5E, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '_' => (0x5F, CharacterSet::G0WithDiacritical(Diacritical::None)),

        '`' => (0x60, CharacterSet::G0),
        'a' => (0x61, CharacterSet::G0),
        'b' => (0x62, CharacterSet::G0),
        'c' => (0x63, CharacterSet::G0),
        'd' => (0x64, CharacterSet::G0),
        'e' => (0x65, CharacterSet::G0),
        'f' => (0x66, CharacterSet::G0),
        'g' => (0x67, CharacterSet::G0),
        'h' => (0x68, CharacterSet::G0),
        'i' => (0x69, CharacterSet::G0),
        'j' => (0x6A, CharacterSet::G0),
        'k' => (0x6B, CharacterSet::G0),
        'l' => (0x6C, CharacterSet::G0),
        'm' => (0x6D, CharacterSet::G0),
        'n' => (0x6E, CharacterSet::G0),
        'o' => (0x6F, CharacterSet::G0),
        'p' => (0x70, CharacterSet::G0),
        'q' => (0x71, CharacterSet::G0),
        'r' => (0x72, CharacterSet::G0),
        's' => (0x73, CharacterSet::G0),
        't' => (0x74, CharacterSet::G0),
        'u' => (0x75, CharacterSet::G0),
        'v' => (0x76, CharacterSet::G0),
        'w' => (0x77, CharacterSet::G0),
        'x' => (0x78, CharacterSet::G0),
        'y' => (0x79, CharacterSet::G0),
        'z' => (0x7A, CharacterSet::G0),
        '{' => (0x7B, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '|' => (0x7C, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '}' => (0x7D, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '~' => (0x7E, CharacterSet::G0WithDiacritical(Diacritical::None)),
        '■' => (0x7F, CharacterSet::G0),

        '\u{E000}' => (0x0, CharacterSet::G0),
        '\u{E001}' => (0x1, CharacterSet::G0),
        '\u{E002}' => (0x2, CharacterSet::G0),
        '\u{E003}' => (0x3, CharacterSet::G0),
        '\u{E004}' => (0x4, CharacterSet::G0),
        '\u{E005}' => (0x5, CharacterSet::G0),
        '\u{E006}' => (0x6, CharacterSet::G0),
        '\u{E007}' => (0x7, CharacterSet::G0),
        '\u{E008}' => (0x8, CharacterSet::G0),
        '\u{E009}' => (0x9, CharacterSet::G0),
        '\u{E00A}' => (0xA, CharacterSet::G0),
        '\u{E00B}' => (0xB, CharacterSet::G0),
        '\u{E00C}' => (0xC, CharacterSet::G0),
        '\u{E00D}' => (0xD, CharacterSet::G0),
        '\u{E00E}' => (0xE, CharacterSet::G0),
        '\u{E00F}' => (0xF, CharacterSet::G0),
        '\u{E010}' => (0x10, CharacterSet::G0),
        '\u{E011}' => (0x11, CharacterSet::G0),
        '\u{E012}' => (0x12, CharacterSet::G0),
        '\u{E013}' => (0x13, CharacterSet::G0),
        '\u{E014}' => (0x14, CharacterSet::G0),
        '\u{E015}' => (0x15, CharacterSet::G0),
        '\u{E016}' => (0x16, CharacterSet::G0),
        '\u{E017}' => (0x17, CharacterSet::G0),
        '\u{E018}' => (0x18, CharacterSet::G0),
        '\u{E019}' => (0x19, CharacterSet::G0),
        '\u{E01A}' => (0x1A, CharacterSet::G0),
        '\u{E01B}' => (0x1B, CharacterSet::G0),
        '\u{E01C}' => (0x1C, CharacterSet::G0),
        '\u{E01D}' => (0x1D, CharacterSet::G0),
        '\u{E01E}' => (0x1E, CharacterSet::G0),
        '\u{E01F}' => (0x1F, CharacterSet::G0),
        '\u{E020}' => (0x20, CharacterSet::G0),
        '\u{E021}' => (0x21, CharacterSet::G0),
        '\u{E022}' => (0x22, CharacterSet::G0),
        '\u{E023}' => (0x23, CharacterSet::G0),
        '\u{E024}' => (0x24, CharacterSet::G0),
        '\u{E025}' => (0x25, CharacterSet::G0),
        '\u{E026}' => (0x26, CharacterSet::G0),
        '\u{E027}' => (0x27, CharacterSet::G0),
        '\u{E028}' => (0x28, CharacterSet::G0),
        '\u{E029}' => (0x29, CharacterSet::G0),
        '\u{E02A}' => (0x2A, CharacterSet::G0),
        '\u{E02B}' => (0x2B, CharacterSet::G0),
        '\u{E02C}' => (0x2C, CharacterSet::G0),
        '\u{E02D}' => (0x2D, CharacterSet::G0),
        '\u{E02E}' => (0x2E, CharacterSet::G0),
        '\u{E02F}' => (0x2F, CharacterSet::G0),
        '\u{E030}' => (0x30, CharacterSet::G0),
        '\u{E031}' => (0x31, CharacterSet::G0),
        '\u{E032}' => (0x32, CharacterSet::G0),
        '\u{E033}' => (0x33, CharacterSet::G0),
        '\u{E034}' => (0x34, CharacterSet::G0),
        '\u{E035}' => (0x35, CharacterSet::G0),
        '\u{E036}' => (0x36, CharacterSet::G0),
        '\u{E037}' => (0x37, CharacterSet::G0),
        '\u{E038}' => (0x38, CharacterSet::G0),
        '\u{E039}' => (0x39, CharacterSet::G0),
        '\u{E03A}' => (0x3A, CharacterSet::G0),
        '\u{E03B}' => (0x3B, CharacterSet::G0),
        '\u{E03C}' => (0x3C, CharacterSet::G0),
        '\u{E03D}' => (0x3D, CharacterSet::G0),
        '\u{E03E}' => (0x3E, CharacterSet::G0),
        '\u{E03F}' => (0x3F, CharacterSet::G0),
        '\u{E040}' => (0x40, CharacterSet::G0),
        '\u{E041}' => (0x41, CharacterSet::G0),
        '\u{E042}' => (0x42, CharacterSet::G0),
        '\u{E043}' => (0x43, CharacterSet::G0),
        '\u{E044}' => (0x44, CharacterSet::G0),
        '\u{E045}' => (0x45, CharacterSet::G0),
        '\u{E046}' => (0x46, CharacterSet::G0),
        '\u{E047}' => (0x47, CharacterSet::G0),
        '\u{E048}' => (0x48, CharacterSet::G0),
        '\u{E049}' => (0x49, CharacterSet::G0),
        '\u{E04A}' => (0x4A, CharacterSet::G0),
        '\u{E04B}' => (0x4B, CharacterSet::G0),
        '\u{E04C}' => (0x4C, CharacterSet::G0),
        '\u{E04D}' => (0x4D, CharacterSet::G0),
        '\u{E04E}' => (0x4E, CharacterSet::G0),
        '\u{E04F}' => (0x4F, CharacterSet::G0),
        '\u{E050}' => (0x50, CharacterSet::G0),
        '\u{E051}' => (0x51, CharacterSet::G0),
        '\u{E052}' => (0x52, CharacterSet::G0),
        '\u{E053}' => (0x53, CharacterSet::G0),
        '\u{E054}' => (0x54, CharacterSet::G0),
        '\u{E055}' => (0x55, CharacterSet::G0),
        '\u{E056}' => (0x56, CharacterSet::G0),
        '\u{E057}' => (0x57, CharacterSet::G0),
        '\u{E058}' => (0x58, CharacterSet::G0),
        '\u{E059}' => (0x59, CharacterSet::G0),
        '\u{E05A}' => (0x5A, CharacterSet::G0),
        '\u{E05B}' => (0x5B, CharacterSet::G0),
        '\u{E05C}' => (0x5C, CharacterSet::G0),
        '\u{E05D}' => (0x5D, CharacterSet::G0),
        '\u{E05E}' => (0x5E, CharacterSet::G0),
        '\u{E05F}' => (0x5F, CharacterSet::G0),
        '\u{E060}' => (0x60, CharacterSet::G0),
        '\u{E061}' => (0x61, CharacterSet::G0),
        '\u{E062}' => (0x62, CharacterSet::G0),
        '\u{E063}' => (0x63, CharacterSet::G0),
        '\u{E064}' => (0x64, CharacterSet::G0),
        '\u{E065}' => (0x65, CharacterSet::G0),
        '\u{E066}' => (0x66, CharacterSet::G0),
        '\u{E067}' => (0x67, CharacterSet::G0),
        '\u{E068}' => (0x68, CharacterSet::G0),
        '\u{E069}' => (0x69, CharacterSet::G0),
        '\u{E06A}' => (0x6A, CharacterSet::G0),
        '\u{E06B}' => (0x6B, CharacterSet::G0),
        '\u{E06C}' => (0x6C, CharacterSet::G0),
        '\u{E06D}' => (0x6D, CharacterSet::G0),
        '\u{E06E}' => (0x6E, CharacterSet::G0),
        '\u{E06F}' => (0x6F, CharacterSet::G0),
        '\u{E070}' => (0x70, CharacterSet::G0),
        '\u{E071}' => (0x71, CharacterSet::G0),
        '\u{E072}' => (0x72, CharacterSet::G0),
        '\u{E073}' => (0x73, CharacterSet::G0),
        '\u{E074}' => (0x74, CharacterSet::G0),
        '\u{E075}' => (0x75, CharacterSet::G0),
        '\u{E076}' => (0x76, CharacterSet::G0),
        '\u{E077}' => (0x77, CharacterSet::G0),
        '\u{E078}' => (0x78, CharacterSet::G0),
        '\u{E079}' => (0x79, CharacterSet::G0),
        '\u{E07A}' => (0x7A, CharacterSet::G0),
        '\u{E07B}' => (0x7B, CharacterSet::G0),
        '\u{E07C}' => (0x7C, CharacterSet::G0),
        '\u{E07D}' => (0x7D, CharacterSet::G0),
        '\u{E07E}' => (0x7E, CharacterSet::G0),
        '\u{E07F}' => (0x7F, CharacterSet::G0),

        '¡' => (0x21, CharacterSet::G2),
        '¢' => (0x22, CharacterSet::G2),
        '£' => (0x23, CharacterSet::G2),
        '$' => (0x24, CharacterSet::G2),
        '¥' => (0x25, CharacterSet::G2),
        //'#' => (0x26, CharacterSet::G2),
        '§' => (0x27, CharacterSet::G2),
        //'¤' => (0x28, CharacterSet::G2),
        '‘' => (0x29, CharacterSet::G2),
        '“' => (0x2A, CharacterSet::G2),
        '«' => (0x2B, CharacterSet::G2),
        '←' => (0x2C, CharacterSet::G2),
        '↑' => (0x2D, CharacterSet::G2),
        '→' => (0x2E, CharacterSet::G2),
        '↓' => (0x2F, CharacterSet::G2),
        '°' => (0x30, CharacterSet::G2),
        '±' => (0x31, CharacterSet::G2),
        '²' => (0x32, CharacterSet::G2),
        '³' => (0x33, CharacterSet::G2),
        '×' => (0x34, CharacterSet::G2),
        'µ' => (0x35, CharacterSet::G2),
        '¶' => (0x36, CharacterSet::G2),
        '⋅' => (0x37, CharacterSet::G2),
        '÷' => (0x38, CharacterSet::G2),
        '’' => (0x39, CharacterSet::G2),
        '”' => (0x3A, CharacterSet::G2),
        '»' => (0x3B, CharacterSet::G2),
        '¼' => (0x3C, CharacterSet::G2),
        '½' => (0x3D, CharacterSet::G2),
        '¾' => (0x3E, CharacterSet::G2),
        '¿' => (0x3F, CharacterSet::G2),
        //' ' => (0x40, CharacterSet::G2),
        '̀' => (0x41, CharacterSet::G2),
        '́' => (0x42, CharacterSet::G2),
        '̂' => (0x43, CharacterSet::G2),
        '̃' => (0x44, CharacterSet::G2),
        '̄' => (0x45, CharacterSet::G2),
        '̆' => (0x46, CharacterSet::G2),
        '̇' => (0x47, CharacterSet::G2),
        '̈' => (0x48, CharacterSet::G2),
        '̣' => (0x49, CharacterSet::G2),
        '̊' => (0x4A, CharacterSet::G2),
        '̧' => (0x4B, CharacterSet::G2),
        '̲' => (0x4C, CharacterSet::G2),
        '̋' => (0x4D, CharacterSet::G2),
        '̨' => (0x4E, CharacterSet::G2),
        '̌' => (0x4F, CharacterSet::G2),
        '—' => (0x50, CharacterSet::G2),
        '―' => (0x50, CharacterSet::G2),
        '¹' => (0x51, CharacterSet::G2),
        '®' => (0x52, CharacterSet::G2),
        '©' => (0x53, CharacterSet::G2),
        '™' => (0x54, CharacterSet::G2),
        '♪' => (0x55, CharacterSet::G2),
        '🎵' => (0x55, CharacterSet::G2),
        '₠' => (0x56, CharacterSet::G2),
        '‰' => (0x57, CharacterSet::G2),
        'α' => (0x58, CharacterSet::G2),
        '⅛' => (0x5C, CharacterSet::G2),
        '⅜' => (0x5D, CharacterSet::G2),
        '⅝' => (0x5E, CharacterSet::G2),
        '⅞' => (0x5F, CharacterSet::G2),
        'Ω' => (0x60, CharacterSet::G2),
        'Æ' => (0x61, CharacterSet::G2),
        'Đ' => (0x62, CharacterSet::G2),
        'ª' => (0x63, CharacterSet::G2),
        'Ħ' => (0x64, CharacterSet::G2),
        'Ĳ' => (0x66, CharacterSet::G2),
        'Ŀ' => (0x67, CharacterSet::G2),
        'Ł' => (0x68, CharacterSet::G2),
        'Ø' => (0x69, CharacterSet::G2),
        'Œ' => (0x6A, CharacterSet::G2),
        'º' => (0x6B, CharacterSet::G2),
        'Þ' => (0x6C, CharacterSet::G2),
        'Ŧ' => (0x6D, CharacterSet::G2),
        'Ŋ' => (0x6E, CharacterSet::G2),
        'ŉ' => (0x6F, CharacterSet::G2),
        'ĸ' => (0x70, CharacterSet::G2),
        'æ' => (0x71, CharacterSet::G2),
        'đ' => (0x72, CharacterSet::G2),
        'ð' => (0x73, CharacterSet::G2),
        'ħ' => (0x74, CharacterSet::G2),
        'ı' => (0x75, CharacterSet::G2),
        'ĳ' => (0x76, CharacterSet::G2),
        'ŀ' => (0x77, CharacterSet::G2),
        'ł' => (0x78, CharacterSet::G2),
        'ø' => (0x79, CharacterSet::G2),
        'œ' => (0x7A, CharacterSet::G2),
        'ß' => (0x7B, CharacterSet::G2),
        'þ' => (0x7C, CharacterSet::G2),
        'ŧ' => (0x7D, CharacterSet::G2),
        'ŋ' => (0x7E, CharacterSet::G2),

        '🬼' => (0x20, CharacterSet::G3),
        '🬽' => (0x21, CharacterSet::G3),
        '🬾' => (0x22, CharacterSet::G3),
        '🬿' => (0x23, CharacterSet::G3),
        '🭀' => (0x24, CharacterSet::G3),
        '◣' => (0x25, CharacterSet::G3),
        '🭁' => (0x26, CharacterSet::G3),
        '🭂' => (0x27, CharacterSet::G3),
        '🭃' => (0x28, CharacterSet::G3),
        '🭄' => (0x29, CharacterSet::G3),
        '🭅' => (0x2A, CharacterSet::G3),
        '🭆' => (0x2B, CharacterSet::G3),
        '🭨' => (0x2C, CharacterSet::G3),
        '🭩' => (0x2D, CharacterSet::G3),
        '🭰' => (0x2E, CharacterSet::G3),
        '▒' => (0x2F, CharacterSet::G3),
        '🭇' => (0x30, CharacterSet::G3),
        '🭈' => (0x31, CharacterSet::G3),
        '🭉' => (0x32, CharacterSet::G3),
        '🭊' => (0x33, CharacterSet::G3),
        '🭋' => (0x34, CharacterSet::G3),
        '◢' => (0x35, CharacterSet::G3),
        '🭌' => (0x36, CharacterSet::G3),
        '🭍' => (0x37, CharacterSet::G3),
        '🭎' => (0x38, CharacterSet::G3),
        '🭏' => (0x39, CharacterSet::G3),
        '🭐' => (0x3A, CharacterSet::G3),
        '🭑' => (0x3B, CharacterSet::G3),
        '🭪' => (0x3C, CharacterSet::G3),
        '🭫' => (0x3D, CharacterSet::G3),
        '🭵' => (0x3E, CharacterSet::G3),
        '█' => (0x3F, CharacterSet::G3),
        '┷' => (0x40, CharacterSet::G3),
        '┯' => (0x41, CharacterSet::G3),
        '┝' => (0x42, CharacterSet::G3),
        '┥' => (0x43, CharacterSet::G3),
        '🮤' => (0x44, CharacterSet::G3),
        '🮥' => (0x45, CharacterSet::G3),
        '🮦' => (0x46, CharacterSet::G3),
        '🮧' => (0x47, CharacterSet::G3),
        '🮠' => (0x48, CharacterSet::G3),
        '🮡' => (0x49, CharacterSet::G3),
        '🮢' => (0x4A, CharacterSet::G3),
        '🮣' => (0x4B, CharacterSet::G3),
        '┿' => (0x4C, CharacterSet::G3),
        '•' => (0x4D, CharacterSet::G3),
        '●' => (0x4E, CharacterSet::G3),
        '○' => (0x4F, CharacterSet::G3),
        '│' => (0x50, CharacterSet::G3),
        '─' => (0x51, CharacterSet::G3),
        '┌' => (0x52, CharacterSet::G3),
        '┐' => (0x53, CharacterSet::G3),
        '└' => (0x54, CharacterSet::G3),
        '┘' => (0x55, CharacterSet::G3),
        '├' => (0x56, CharacterSet::G3),
        '┤' => (0x57, CharacterSet::G3),
        '┬' => (0x58, CharacterSet::G3),
        '┴' => (0x59, CharacterSet::G3),
        '┼' => (0x5A, CharacterSet::G3),
        '⭢' => (0x5B, CharacterSet::G3),
        '⭠' => (0x5C, CharacterSet::G3),
        '⭡' => (0x5D, CharacterSet::G3),
        '⭣' => (0x5E, CharacterSet::G3),
        '🭒' => (0x60, CharacterSet::G3),
        '🭓' => (0x61, CharacterSet::G3),
        '🭔' => (0x62, CharacterSet::G3),
        '🭕' => (0x63, CharacterSet::G3),
        '🭖' => (0x64, CharacterSet::G3),
        '◥' => (0x65, CharacterSet::G3),
        '🭗' => (0x66, CharacterSet::G3),
        '🭘' => (0x67, CharacterSet::G3),
        '🭙' => (0x68, CharacterSet::G3),
        '🭚' => (0x69, CharacterSet::G3),
        '🭛' => (0x6A, CharacterSet::G3),
        '🭜' => (0x6B, CharacterSet::G3),
        '🭬' => (0x6C, CharacterSet::G3),
        '🭭' => (0x6D, CharacterSet::G3),
        '🭝' => (0x70, CharacterSet::G3),
        '🭞' => (0x71, CharacterSet::G3),
        '🭟' => (0x72, CharacterSet::G3),
        '🭠' => (0x73, CharacterSet::G3),
        '🭡' => (0x74, CharacterSet::G3),
        '◤' => (0x75, CharacterSet::G3),
        '🭢' => (0x76, CharacterSet::G3),
        '🭣' => (0x77, CharacterSet::G3),
        '🭤' => (0x78, CharacterSet::G3),
        '🭥' => (0x79, CharacterSet::G3),
        '🭦' => (0x7A, CharacterSet::G3),
        '🭧' => (0x7B, CharacterSet::G3),
        '🭮' => (0x7C, CharacterSet::G3),
        '🭯' => (0x7D, CharacterSet::G3),

        'À' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'à' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'È' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'è' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'Ì' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'ì' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'Ǹ' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'ǹ' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'Ò' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'ò' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'Ù' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'ù' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'Ẁ' => (0x57, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'ẁ' => (0x77, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'Ỳ' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::Grave)),
        'ỳ' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::Grave)),

        'Á' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'á' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ć' => (0x43, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ć' => (0x63, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'É' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'é' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ǵ' => (0x47, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ǵ' => (0x67, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Í' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'í' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ḱ' => (0x4B, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ḱ' => (0x6B, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ĺ' => (0x4C, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ĺ' => (0x6C, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ḿ' => (0x4D, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ḿ' => (0x6D, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ń' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ń' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ó' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ó' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ṕ' => (0x50, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ṕ' => (0x70, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ŕ' => (0x52, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ŕ' => (0x72, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ś' => (0x53, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ś' => (0x73, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ú' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ú' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ẃ' => (0x57, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ẃ' => (0x77, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ý' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ý' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'Ź' => (0x5A, CharacterSet::G0WithDiacritical(Diacritical::Acute)),
        'ź' => (0x7A, CharacterSet::G0WithDiacritical(Diacritical::Acute)),

        'Â' => (
            0x41,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'â' => (
            0x61,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ĉ' => (
            0x43,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ĉ' => (
            0x63,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ê' => (
            0x45,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ê' => (
            0x65,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ĝ' => (
            0x47,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ĝ' => (
            0x67,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ĥ' => (
            0x48,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ĥ' => (
            0x68,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Î' => (
            0x49,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'î' => (
            0x69,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ĵ' => (
            0x4A,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ĵ' => (
            0x6A,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ô' => (
            0x4F,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ô' => (
            0x6F,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ŝ' => (
            0x53,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ŝ' => (
            0x73,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Û' => (
            0x55,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'û' => (
            0x75,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ŵ' => (
            0x57,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ŵ' => (
            0x77,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ŷ' => (
            0x59,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ŷ' => (
            0x79,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'Ẑ' => (
            0x5A,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),
        'ẑ' => (
            0x7A,
            CharacterSet::G0WithDiacritical(Diacritical::Circumflex),
        ),

        'Ã' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'ã' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Ẽ' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'ẽ' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Ĩ' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'ĩ' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Ñ' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'ñ' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Õ' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'õ' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Ũ' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'ũ' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Ṽ' => (0x56, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'ṽ' => (0x76, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),
        'Ỹ' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::Tilde)),

        'Ā' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ā' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'Ē' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ē' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'Ḡ' => (0x47, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ḡ' => (0x67, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'Ī' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ī' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'Ō' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ō' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'Ū' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ū' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'Ȳ' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::Macron)),
        'ȳ' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::Macron)),

        'Ă' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'ă' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'Ĕ' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'ĕ' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'Ğ' => (0x47, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'ğ' => (0x67, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'Ĭ' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'ĭ' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'Ŏ' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'ŏ' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'Ŭ' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Breve)),
        'ŭ' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Breve)),

        'Ȧ' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ȧ' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ḃ' => (0x42, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ḃ' => (0x62, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ċ' => (0x43, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ċ' => (0x63, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ḋ' => (0x44, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ḋ' => (0x64, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ė' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ė' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ḟ' => (0x46, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ḟ' => (0x66, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ġ' => (0x47, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ġ' => (0x67, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ḣ' => (0x48, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ḣ' => (0x68, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'İ' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ṁ' => (0x4D, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ṁ' => (0x6D, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ṅ' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ṅ' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ȯ' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ȯ' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ṗ' => (0x50, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ṗ' => (0x70, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ṙ' => (0x52, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ṙ' => (0x72, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ṡ' => (0x53, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ṡ' => (0x73, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ṫ' => (0x54, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ṫ' => (0x74, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ẇ' => (0x57, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ẇ' => (0x77, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ẋ' => (0x58, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ẋ' => (0x78, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ẏ' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ẏ' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'Ż' => (0x5A, CharacterSet::G0WithDiacritical(Diacritical::Dot)),
        'ż' => (0x7A, CharacterSet::G0WithDiacritical(Diacritical::Dot)),

        'Ä' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ä' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ë' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ë' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ḧ' => (0x48, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ḧ' => (0x68, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ï' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ï' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ö' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ö' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ẗ' => (0x74, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ü' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ü' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ẅ' => (0x57, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ẅ' => (0x77, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ẍ' => (0x58, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ẍ' => (0x78, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'Ÿ' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),
        'ÿ' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::Umlaut)),

        'Ạ' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ạ' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ḅ' => (0x42, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ḅ' => (0x62, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ḍ' => (0x44, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ḍ' => (0x64, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ẹ' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ẹ' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ḥ' => (0x48, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ḥ' => (0x68, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ị' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ị' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ḳ' => (0x4B, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ḳ' => (0x6B, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ḷ' => (0x4C, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ḷ' => (0x6C, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ṃ' => (0x4D, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ṃ' => (0x6D, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ṇ' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ṇ' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ọ' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ọ' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ṛ' => (0x52, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ṛ' => (0x72, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ṣ' => (0x53, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ṣ' => (0x73, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ṭ' => (0x54, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ṭ' => (0x74, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ụ' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ụ' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ṿ' => (0x56, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ṿ' => (0x76, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ẉ' => (0x57, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ẉ' => (0x77, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ỵ' => (0x59, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ỵ' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'Ẓ' => (0x5A, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),
        'ẓ' => (0x7A, CharacterSet::G0WithDiacritical(Diacritical::DotBelow)),

        'Å' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Ring)),
        'å' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Ring)),
        'Ů' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Ring)),
        'ů' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Ring)),
        'ẘ' => (0x77, CharacterSet::G0WithDiacritical(Diacritical::Ring)),
        'ẙ' => (0x79, CharacterSet::G0WithDiacritical(Diacritical::Ring)),

        'Ç' => (0x43, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ç' => (0x63, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ḑ' => (0x44, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ḑ' => (0x64, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ȩ' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ȩ' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ģ' => (0x47, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ģ' => (0x67, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ḩ' => (0x48, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ḩ' => (0x68, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ķ' => (0x4B, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ķ' => (0x6B, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ļ' => (0x4C, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ļ' => (0x6C, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ņ' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ņ' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ŗ' => (0x52, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ŗ' => (0x72, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ş' => (0x53, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ş' => (0x73, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'Ţ' => (0x54, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),
        'ţ' => (0x74, CharacterSet::G0WithDiacritical(Diacritical::Cedilla)),

        'Ő' => (
            0x4F,
            CharacterSet::G0WithDiacritical(Diacritical::DoubleAcute),
        ),
        'ő' => (
            0x6F,
            CharacterSet::G0WithDiacritical(Diacritical::DoubleAcute),
        ),
        'Ű' => (
            0x55,
            CharacterSet::G0WithDiacritical(Diacritical::DoubleAcute),
        ),
        'ű' => (
            0x75,
            CharacterSet::G0WithDiacritical(Diacritical::DoubleAcute),
        ),

        'Ą' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'ą' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'Ę' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'ę' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'Į' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'į' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'Ǫ' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'ǫ' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'Ų' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),
        'ų' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Ogonek)),

        'Ǎ' => (0x41, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǎ' => (0x61, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Č' => (0x43, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'č' => (0x63, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ď' => (0x44, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ď' => (0x64, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ě' => (0x45, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ě' => (0x65, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ǧ' => (0x47, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǧ' => (0x67, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ȟ' => (0x48, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ȟ' => (0x68, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ǐ' => (0x49, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǐ' => (0x69, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǰ' => (0x6A, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ǩ' => (0x4B, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǩ' => (0x6B, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ľ' => (0x6C, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ň' => (0x4E, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ň' => (0x6E, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ǒ' => (0x4F, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǒ' => (0x6F, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ř' => (0x52, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ř' => (0x72, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Š' => (0x53, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'š' => (0x73, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ť' => (0x54, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ť' => (0x74, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ǔ' => (0x55, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ǔ' => (0x75, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'Ž' => (0x5A, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        'ž' => (0x7A, CharacterSet::G0WithDiacritical(Diacritical::Caron)),
        _ => return None,
    })
};

/// Converts an utf-8 char into a teletext encoded char
///
/// # Arguments
/// * `ch` - input char
/// * `subset` - Which character subset is currently used
pub fn char_to_teletext(
    ch: char,
    subset: NationalOptionCharacterSubset,
) -> Option<(TeletextChar, CharacterSet)> {
    subset
        .has_char(ch)
        .map(|code| (TeletextChar(code), CharacterSet::G0))
        .or_else(|| LATIN_TELETEXT_CHARS(ch).map(|res| (TeletextChar(res.0), res.1)))
}
